version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
     - /mnt/pgdata:/var/lib/postgresql/data
    environment:
     - TZ=Australia/Brisbane
  cache:
    build: ontocache
    image: ontocache:latest
    depends_on:
      - ontoserver_stateful
      - ontoserver_stateless
    ports:
      - "8080:80"
#      - "8443:443"
    environment:
      - TZ=Australia/Brisbane
  ontoserver_stateful:
    image: aehrc/ontoserver:ctsa-5.0
    depends_on:
     - db
    environment:
      - ONTOSERVER_INSECURE=true
      - atom.syndication.publish.enabled=true
      - ontoserver.security.readOnly.api=true
      - ontoserver.security.readOnly.fhir=true
      - ontoserver.security.readOnly.synd=true
      - JAVA_OPTS=-Xmx12G
      - TZ=Australia/Brisbane
    volumes:
     - /mnt/onto:/var/onto
    logging:
      options:
        max-size: 1024m
  ontoserver_stateless:
    image: aehrc/ontoserver:ctsa-5.0
    depends_on:
     - db
    environment:
      - ONTOSERVER_INSECURE=true
      - atom.syndication.publish.enabled=true
      - ontoserver.security.readOnly.api=true
      - ontoserver.security.readOnly.fhir=true
      - ontoserver.security.readOnly.synd=true
      - JAVA_OPTS=-Xmx12G
      - TZ=Australia/Brisbane
    volumes:
     - /mnt/onto:/var/onto
    logging:
      options:
        max-size: 1024m
